version: '3.8'

services:
  db-init:
    image: python:3.9-alpine
    container_name: atheer-db-init
    volumes:
      - ./populate_database.py:/app/populate_database.py
      - ./towers.geojson:/app/towers.geojson
    working_dir: /app
    command: >
      sh -c "pip install psycopg2-binary &&
             python populate_database.py"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: atheer
      DB_USER: atheer
      DB_PASSWORD: atheer123